/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "v1.8.0_RC1-14-g306b3742-sophon-1.8.0"
#endif /* AVUTIL_FFVERSION_H */
